"""
POLAROPS — Seed Data
Coherent fictional expedition data for demonstration purposes.

⚠ SYNTHETIC / SIMULATED PROTOTYPE DATA
This data does NOT represent actual NCPOR expeditions or operations.
"""

import asyncio
import uuid
from datetime import datetime
from database import engine, Base, AsyncSessionLocal
from models.models import (
    Station, Personnel, Asset, Inventory, Cargo,
    Mission, Dependency, Alert, AuditLog, Disruption
)


# ─── Stations ───────────────────────────────────────────────────────────────
STATIONS = [
    Station(id="STA-01", code="STA-01", name="Bharati Station",
            location="Prydz Bay, East Antarctica", latitude=-69.4065, longitude=76.1925,
            status="Operational", capacity=48, personnel_count=18, fuel_level=72.0),
    Station(id="STA-02", code="STA-02", name="Maitri Station",
            location="Schirmacher Oasis, East Antarctica", latitude=-70.7667, longitude=11.7333,
            status="Operational", capacity=42, personnel_count=12, fuel_level=88.0),
    Station(id="STA-03", code="STA-03", name="Field Camp Alpha",
            location="Prydz Bay Ice Shelf, Sector B12", latitude=-69.8500, longitude=77.4000,
            status="Limited", capacity=12, personnel_count=5, fuel_level=45.0),
]

# ─── Personnel ──────────────────────────────────────────────────────────────
PERSONNEL = [
    # Team Alpha — Bharati
    Personnel(id="P-001", name="Dr. Anjali Mehta", role="Expedition Commander",
              team="Command", station_id="STA-01", status="Available",
              current_location="Bharati Station", assigned_mission_id=None, specialization="Polar Science"),
    Personnel(id="P-002", name="Cmdr. Rohan Kapoor", role="Logistics Officer",
              team="Command", station_id="STA-01", status="Available",
              current_location="Bharati Station", assigned_mission_id=None, specialization="Logistics"),
    Personnel(id="P-003", name="Dr. Priya Nair", role="Researcher",
              team="Alpha", station_id="STA-01", status="Assigned",
              current_location="Bharati Station", assigned_mission_id="M-021", specialization="Glaciology"),
    Personnel(id="P-004", name="Eng. Siddharth Kumar", role="Mechanical Engineer",
              team="Alpha", station_id="STA-01", status="Assigned",
              current_location="Bharati Station", assigned_mission_id="M-027", specialization="Generator Systems"),
    Personnel(id="P-005", name="Eng. Kavya Reddy", role="Electrical Engineer",
              team="Alpha", station_id="STA-01", status="Assigned",
              current_location="Bharati Station", assigned_mission_id="M-027", specialization="Power Systems"),
    Personnel(id="P-006", name="Dr. Vikram Singh", role="Doctor",
              team="Alpha", station_id="STA-01", status="Available",
              current_location="Bharati Station", assigned_mission_id=None, specialization="Emergency Medicine"),
    Personnel(id="P-007", name="Tech. Arjun Sharma", role="Technician",
              team="Alpha", station_id="STA-01", status="In Transit",
              current_location="En Route to Field Camp Alpha", assigned_mission_id="M-038", specialization="Electronics"),
    Personnel(id="P-008", name="Spec. Neha Gupta", role="Communications Specialist",
              team="Alpha", station_id="STA-01", status="Assigned",
              current_location="Bharati Station", assigned_mission_id="M-041", specialization="Satellite Comms"),
    # Team Beta — Maitri
    Personnel(id="P-009", name="Dr. Amit Joshi", role="Researcher",
              team="Beta", station_id="STA-02", status="Available",
              current_location="Maitri Station", assigned_mission_id=None, specialization="Meteorology"),
    Personnel(id="P-010", name="Eng. Sunita Rao", role="Mechanical Engineer",
              team="Beta", station_id="STA-02", status="Available",
              current_location="Maitri Station", assigned_mission_id=None, specialization="Vehicles"),
    Personnel(id="P-011", name="Tech. Rahul Das", role="Technician",
              team="Beta", station_id="STA-02", status="Assigned",
              current_location="Maitri Station", assigned_mission_id="M-031", specialization="Field Equipment"),
    Personnel(id="P-012", name="Spec. Meena Pillai", role="Communications Specialist",
              team="Beta", station_id="STA-02", status="Available",
              current_location="Maitri Station", assigned_mission_id=None, specialization="Radio"),
    Personnel(id="P-013", name="Dr. Kiran Yadav", role="Researcher",
              team="Beta", station_id="STA-02", status="Assigned",
              current_location="Maitri Station", assigned_mission_id="M-031", specialization="Oceanography"),
    # Team Gamma — Field Camp
    Personnel(id="P-014", name="Eng. Deepak Verma", role="Mechanical Engineer",
              team="Gamma", station_id="STA-03", status="Assigned",
              current_location="Field Camp Alpha", assigned_mission_id="M-021", specialization="Mechanical"),
    Personnel(id="P-015", name="Tech. Pooja Iyer", role="Technician",
              team="Gamma", station_id="STA-03", status="Assigned",
              current_location="Field Camp Alpha", assigned_mission_id="M-021", specialization="Instruments"),
    Personnel(id="P-016", name="Dr. Suresh Nair", role="Researcher",
              team="Gamma", station_id="STA-03", status="Assigned",
              current_location="Field Camp Alpha", assigned_mission_id="M-021", specialization="Geology"),
    Personnel(id="P-017", name="Tech. Arun Krishnan", role="Technician",
              team="Alpha", station_id="STA-01", status="Available",
              current_location="Bharati Station", assigned_mission_id=None, specialization="Maintenance"),
    Personnel(id="P-018", name="Eng. Lata Sharma", role="Electrical Engineer",
              team="Beta", station_id="STA-02", status="Available",
              current_location="Maitri Station", assigned_mission_id=None, specialization="Solar Power"),
    Personnel(id="P-019", name="Dr. Ravi Menon", role="Researcher",
              team="Alpha", station_id="STA-01", status="Medical",
              current_location="Bharati Medical Bay", assigned_mission_id=None, specialization="Biology"),
    Personnel(id="P-020", name="Tech. Anita Pillai", role="Logistics Officer",
              team="Command", station_id="STA-01", status="Available",
              current_location="Bharati Station", assigned_mission_id=None, specialization="Supply Chain"),
    Personnel(id="P-021", name="Eng. Rajesh Gupta", role="Mechanical Engineer",
              team="Alpha", station_id="STA-01", status="Available",
              current_location="Bharati Station", assigned_mission_id=None, specialization="Cryogenics"),
    Personnel(id="P-022", name="Tech. Prashant Desai", role="Technician",
              team="Beta", station_id="STA-02", status="Available",
              current_location="Maitri Station", assigned_mission_id=None, specialization="HVAC"),
    Personnel(id="P-023", name="Dr. Shreya Bose", role="Researcher",
              team="Gamma", station_id="STA-03", status="Assigned",
              current_location="Field Camp Alpha", assigned_mission_id="M-021", specialization="Ice Core"),
    Personnel(id="P-024", name="Spec. Kartik Menon", role="Communications Specialist",
              team="Gamma", station_id="STA-03", status="Available",
              current_location="Field Camp Alpha", assigned_mission_id=None, specialization="Emergency Comms"),
    Personnel(id="P-025", name="Dr. Divya Krishnamurthy", role="Doctor",
              team="Beta", station_id="STA-02", status="Available",
              current_location="Maitri Station", assigned_mission_id=None, specialization="Trauma"),
]

# ─── Assets ─────────────────────────────────────────────────────────────────
ASSETS = [
    Asset(id="A-V01", asset_code="V-01", name="Snow Vehicle 1",
          type="Vehicle", station_id="STA-01", status="Operational",
          condition_score=91.0, fuel_level=78.0, battery_level=95.0,
          maintenance_due="2026-10-15", assigned_mission_id=None),
    Asset(id="A-V02", asset_code="V-02", name="Snow Vehicle 2",
          type="Vehicle", station_id="STA-01", status="Operational",
          condition_score=88.0, fuel_level=65.0, battery_level=88.0,
          maintenance_due="2026-10-22", assigned_mission_id="M-038"),
    Asset(id="A-V03", asset_code="V-03", name="Snow Vehicle 3",
          type="Vehicle", station_id="STA-02", status="Maintenance",
          condition_score=62.0, fuel_level=40.0, battery_level=70.0,
          maintenance_due="2026-09-15", assigned_mission_id=None),
    Asset(id="A-V04", asset_code="V-04", name="Snow Vehicle 4",
          type="Vehicle", station_id="STA-01", status="Operational",
          condition_score=86.0, fuel_level=64.0, battery_level=82.0,
          maintenance_due="2026-11-01", assigned_mission_id=None),
    Asset(id="A-V05", asset_code="V-05", name="Snow Vehicle 5",
          type="Vehicle", station_id="STA-02", status="Operational",
          condition_score=79.0, fuel_level=88.0, battery_level=91.0,
          maintenance_due="2026-10-28", assigned_mission_id="M-031"),
    Asset(id="A-G01", asset_code="G-01", name="Generator Unit 1",
          type="Generator", station_id="STA-01", status="Operational",
          condition_score=88.0, fuel_level=82.0, battery_level=100.0,
          maintenance_due="2026-09-25", assigned_mission_id=None),
    Asset(id="A-G02", asset_code="G-02", name="Generator Unit 2",
          type="Generator", station_id="STA-02", status="Operational",
          condition_score=94.0, fuel_level=91.0, battery_level=100.0,
          maintenance_due="2026-10-10", assigned_mission_id=None),
    Asset(id="A-G03", asset_code="G-03", name="Generator Unit 3 (Primary)",
          type="Generator", station_id="STA-01", status="Operational",
          condition_score=73.0, fuel_level=72.0, battery_level=100.0,
          maintenance_due="2026-09-18", assigned_mission_id="M-027"),
    Asset(id="A-C01", asset_code="COM-01", name="Primary Communication Unit",
          type="Communication", station_id="STA-01", status="Operational",
          condition_score=96.0, fuel_level=100.0, battery_level=100.0,
          maintenance_due="2026-12-01", assigned_mission_id=None),
    Asset(id="A-C02", asset_code="COM-02", name="Backup Communication Unit",
          type="Communication", station_id="STA-02", status="Operational",
          condition_score=92.0, fuel_level=100.0, battery_level=96.0,
          maintenance_due="2026-12-01", assigned_mission_id=None),
    Asset(id="A-V06", asset_code="V-06", name="Snow Vehicle 6",
          type="Vehicle", station_id="STA-03", status="Operational",
          condition_score=75.0, fuel_level=52.0, battery_level=68.0,
          maintenance_due="2026-10-05", assigned_mission_id="M-021"),
]

# ─── Inventory ──────────────────────────────────────────────────────────────
INVENTORY = [
    # Bharati
    Inventory(id="INV-001", item_code="INV-001", item_name="Diesel Fuel",
              category="Fuel", station_id="STA-01",
              quantity=8500.0, unit="Litres", minimum_stock=5000.0, critical_level=2000.0,
              daily_consumption=280.0, reserved_quantity=500.0, next_resupply_days=12),
    Inventory(id="INV-002", item_code="INV-002", item_name="Food Rations",
              category="Food", station_id="STA-01",
              quantity=1200.0, unit="Person-days", minimum_stock=600.0, critical_level=200.0,
              daily_consumption=18.0, reserved_quantity=0.0, next_resupply_days=30),
    Inventory(id="INV-003", item_code="INV-003", item_name="Drinking Water",
              category="Water", station_id="STA-01",
              quantity=4200.0, unit="Litres", minimum_stock=2000.0, critical_level=800.0,
              daily_consumption=90.0, reserved_quantity=0.0, next_resupply_days=25),
    Inventory(id="INV-004", item_code="INV-004", item_name="Medical Kit - Standard",
              category="Medicine", station_id="STA-01",
              quantity=5.0, unit="Kits", minimum_stock=10.0, critical_level=3.0,
              daily_consumption=0.1, reserved_quantity=1.0, next_resupply_days=8),
    Inventory(id="INV-005", item_code="INV-005", item_name="Battery Pack - LiPo",
              category="Battery", station_id="STA-01",
              quantity=24.0, unit="Units", minimum_stock=12.0, critical_level=4.0,
              daily_consumption=0.5, reserved_quantity=4.0, next_resupply_days=20),
    Inventory(id="INV-006", item_code="INV-006", item_name="Vehicle Fuel Additives",
              category="Spare Parts", station_id="STA-01",
              quantity=120.0, unit="Litres", minimum_stock=80.0, critical_level=30.0,
              daily_consumption=4.0, reserved_quantity=0.0, next_resupply_days=15),
    Inventory(id="INV-007", item_code="INV-007", item_name="Research Consumables",
              category="Equipment", station_id="STA-01",
              quantity=340.0, unit="Units", minimum_stock=100.0, critical_level=50.0,
              daily_consumption=8.0, reserved_quantity=20.0, next_resupply_days=21),
    # CRITICAL: Generator Spare Part — the key demo item
    Inventory(id="INV-017", item_code="INV-017", item_name="Generator Exciter Module",
              category="Spare Parts", station_id="STA-01",
              quantity=0.0, unit="Units", minimum_stock=2.0, critical_level=1.0,
              daily_consumption=0.0, reserved_quantity=0.0, next_resupply_days=6),
    # Maitri
    Inventory(id="INV-008", item_code="INV-008", item_name="Diesel Fuel",
              category="Fuel", station_id="STA-02",
              quantity=12000.0, unit="Litres", minimum_stock=5000.0, critical_level=2000.0,
              daily_consumption=210.0, reserved_quantity=0.0, next_resupply_days=18),
    Inventory(id="INV-009", item_code="INV-009", item_name="Food Rations",
              category="Food", station_id="STA-02",
              quantity=960.0, unit="Person-days", minimum_stock=480.0, critical_level=150.0,
              daily_consumption=12.0, reserved_quantity=0.0, next_resupply_days=35),
    Inventory(id="INV-010", item_code="INV-010", item_name="Medical Kit - Standard",
              category="Medicine", station_id="STA-02",
              quantity=18.0, unit="Kits", minimum_stock=8.0, critical_level=3.0,
              daily_consumption=0.08, reserved_quantity=0.0, next_resupply_days=40),
    Inventory(id="INV-011", item_code="INV-011", item_name="Drinking Water",
              category="Water", station_id="STA-02",
              quantity=6800.0, unit="Litres", minimum_stock=2500.0, critical_level=1000.0,
              daily_consumption=72.0, reserved_quantity=0.0, next_resupply_days=30),
    # Maitri has spare generator exciter modules
    Inventory(id="INV-024", item_code="INV-024", item_name="Generator Exciter Module",
              category="Spare Parts", station_id="STA-02",
              quantity=3.0, unit="Units", minimum_stock=1.0, critical_level=1.0,
              daily_consumption=0.0, reserved_quantity=0.0, next_resupply_days=0),
    # Field Camp
    Inventory(id="INV-012", item_code="INV-012", item_name="Diesel Fuel",
              category="Fuel", station_id="STA-03",
              quantity=1800.0, unit="Litres", minimum_stock=1000.0, critical_level=400.0,
              daily_consumption=85.0, reserved_quantity=0.0, next_resupply_days=5),
    Inventory(id="INV-013", item_code="INV-013", item_name="Food Rations",
              category="Food", station_id="STA-03",
              quantity=120.0, unit="Person-days", minimum_stock=60.0, critical_level=25.0,
              daily_consumption=5.0, reserved_quantity=0.0, next_resupply_days=6),
    Inventory(id="INV-014", item_code="INV-014", item_name="Medical Kit - Emergency",
              category="Medicine", station_id="STA-03",
              quantity=2.0, unit="Kits", minimum_stock=3.0, critical_level=1.0,
              daily_consumption=0.05, reserved_quantity=0.0, next_resupply_days=6),
    Inventory(id="INV-015", item_code="INV-015", item_name="Battery Pack - LiPo",
              category="Battery", station_id="STA-03",
              quantity=8.0, unit="Units", minimum_stock=6.0, critical_level=2.0,
              daily_consumption=0.3, reserved_quantity=0.0, next_resupply_days=6),
    Inventory(id="INV-016", item_code="INV-016", item_name="Mechanical Components Kit",
              category="Spare Parts", station_id="STA-01",
              quantity=14.0, unit="Kits", minimum_stock=8.0, critical_level=3.0,
              daily_consumption=0.2, reserved_quantity=2.0, next_resupply_days=10),
]

# ─── Cargo ──────────────────────────────────────────────────────────────────
CARGO = [
    # THE KEY DEMO CARGO — Delayed generator spare
    Cargo(id="C-1042", cargo_code="C-1042",
          description="Generator Exciter Module — Primary replacement for G-03",
          category="Spare Parts", origin="Goa Logistics Hub",
          destination="STA-01", current_location="Colombo Transit Port",
          transport_mode="Sea", weight=48.5, quantity=2,
          priority="Critical", status="Delayed",
          planned_departure="2026-09-01", planned_arrival="2026-09-15",
          actual_arrival=None, delay_days=5,
          linked_mission_id="M-027", linked_inventory_id="INV-017", linked_asset_id="A-G03",
          container_id="CNT-017"),
    # Other cargo
    Cargo(id="C-1038", cargo_code="C-1038",
          description="Research Equipment — Ice Core Drills",
          category="Equipment", origin="IIT Delhi",
          destination="STA-03", current_location="STA-01",
          transport_mode="Land", weight=124.0, quantity=4,
          priority="High", status="In Transit",
          planned_departure="2026-09-10", planned_arrival="2026-09-14",
          actual_arrival=None, delay_days=0,
          linked_mission_id="M-021", linked_inventory_id=None, linked_asset_id=None,
          container_id="CNT-012"),
    Cargo(id="C-1039", cargo_code="C-1039",
          description="Medical Supplies — Standard Kits",
          category="Medicine", origin="Goa Logistics Hub",
          destination="STA-01", current_location="Indian Ocean (Ship-1)",
          transport_mode="Sea", weight=85.0, quantity=12,
          priority="High", status="In Transit",
          planned_departure="2026-09-05", planned_arrival="2026-09-18",
          actual_arrival=None, delay_days=0,
          linked_mission_id=None, linked_inventory_id="INV-004", linked_asset_id=None,
          container_id="CNT-013"),
    Cargo(id="C-1040", cargo_code="C-1040",
          description="Diesel Fuel — Bharati Station Resupply",
          category="Fuel", origin="Cape Town Fuel Depot",
          destination="STA-01", current_location="Cape Town Port",
          transport_mode="Sea", weight=8500.0, quantity=1,
          priority="Critical", status="Packed",
          planned_departure="2026-09-14", planned_arrival="2026-09-28",
          actual_arrival=None, delay_days=0,
          linked_mission_id=None, linked_inventory_id="INV-001", linked_asset_id=None,
          container_id="CNT-014"),
    Cargo(id="C-1041", cargo_code="C-1041",
          description="Battery Packs — LiPo Field Arrays",
          category="Battery", origin="Chennai Tech Park",
          destination="STA-02", current_location="Singapore Transit",
          transport_mode="Air", weight=36.0, quantity=20,
          priority="Normal", status="In Transit",
          planned_departure="2026-09-11", planned_arrival="2026-09-16",
          actual_arrival=None, delay_days=0,
          linked_mission_id=None, linked_inventory_id="INV-005", linked_asset_id=None,
          container_id="CNT-015"),
    Cargo(id="C-1043", cargo_code="C-1043",
          description="Food Rations — Freeze-dried Supplies",
          category="Food", origin="Mumbai Warehouse",
          destination="STA-01", current_location="Indian Ocean (Ship-2)",
          transport_mode="Sea", weight=3200.0, quantity=1,
          priority="Normal", status="In Transit",
          planned_departure="2026-09-08", planned_arrival="2026-09-22",
          actual_arrival=None, delay_days=0,
          linked_mission_id=None, linked_inventory_id="INV-002", linked_asset_id=None,
          container_id="CNT-016"),
    Cargo(id="C-1044", cargo_code="C-1044",
          description="Snow Vehicle V-03 Spare Parts",
          category="Spare Parts", origin="Goa Logistics Hub",
          destination="STA-02", current_location="STA-02",
          transport_mode="Air", weight=62.0, quantity=1,
          priority="High", status="At Station",
          planned_departure="2026-09-05", planned_arrival="2026-09-10",
          actual_arrival="2026-09-10", delay_days=0,
          linked_mission_id=None, linked_inventory_id=None, linked_asset_id="A-V03",
          container_id="CNT-018"),
    Cargo(id="C-1045", cargo_code="C-1045",
          description="Communications Equipment — Satellite Relay Module",
          category="Equipment", origin="ISRO Bangalore",
          destination="STA-01", current_location="Delivered",
          transport_mode="Air", weight=28.0, quantity=1,
          priority="Normal", status="Delivered",
          planned_departure="2026-08-25", planned_arrival="2026-09-01",
          actual_arrival="2026-09-01", delay_days=0,
          linked_mission_id="M-041", linked_inventory_id=None, linked_asset_id="A-C01",
          container_id="CNT-019"),
    Cargo(id="C-1046", cargo_code="C-1046",
          description="Research Consumables — Geological Sampling Kit",
          category="Equipment", origin="NCPOR Goa",
          destination="STA-03", current_location="STA-01",
          transport_mode="Land", weight=45.0, quantity=3,
          priority="Normal", status="In Transit",
          planned_departure="2026-09-12", planned_arrival="2026-09-14",
          actual_arrival=None, delay_days=0,
          linked_mission_id="M-021", linked_inventory_id="INV-007", linked_asset_id=None,
          container_id="CNT-020"),
    Cargo(id="C-1047", cargo_code="C-1047",
          description="Emergency Medical Kit — Trauma Level",
          category="Medicine", origin="AIIMS Delhi",
          destination="STA-03", current_location="Goa Airport",
          transport_mode="Air", weight=18.0, quantity=3,
          priority="High", status="Packed",
          planned_departure="2026-09-14", planned_arrival="2026-09-16",
          actual_arrival=None, delay_days=1,
          linked_mission_id=None, linked_inventory_id="INV-014", linked_asset_id=None,
          container_id="CNT-021"),
    Cargo(id="C-1048", cargo_code="C-1048",
          description="Vehicle Battery Replacements — V-06",
          category="Battery", origin="Bangalore Warehouse",
          destination="STA-03", current_location="Mumbai Airport",
          transport_mode="Air", weight=22.0, quantity=4,
          priority="Normal", status="In Transit",
          planned_departure="2026-09-13", planned_arrival="2026-09-15",
          actual_arrival=None, delay_days=0,
          linked_mission_id=None, linked_inventory_id="INV-015", linked_asset_id="A-V06",
          container_id="CNT-022"),
    Cargo(id="C-1049", cargo_code="C-1049",
          description="Hydraulic Fluid & Heavy Machinery Seal Kits",
          category="Spare Parts", origin="Mumbai Seaport",
          destination="STA-02", current_location="Southern Ocean Transit",
          transport_mode="Sea", weight=180.0, quantity=6,
          priority="Normal", status="In Transit",
          planned_departure="2026-09-08", planned_arrival="2026-09-24",
          actual_arrival=None, delay_days=0,
          linked_mission_id=None, linked_inventory_id="INV-006", linked_asset_id="A-V03",
          container_id="CNT-023"),
    Cargo(id="C-1050", cargo_code="C-1050",
          description="Scientific Weather Balloons & Radiosondes",
          category="Equipment", origin="IMD Pune",
          destination="STA-02", current_location="Cape Town Airport",
          transport_mode="Air", weight=42.0, quantity=50,
          priority="High", status="Packed",
          planned_departure="2026-09-15", planned_arrival="2026-09-18",
          actual_arrival=None, delay_days=0,
          linked_mission_id="M-031", linked_inventory_id=None, linked_asset_id=None,
          container_id="CNT-024"),
    Cargo(id="C-1051", cargo_code="C-1051",
          description="Water Desalination Filter Membranes",
          category="Equipment", origin="Chennai Port",
          destination="STA-01", current_location="Indian Ocean (Ship-1)",
          transport_mode="Sea", weight=95.0, quantity=8,
          priority="High", status="In Transit",
          planned_departure="2026-09-04", planned_arrival="2026-09-19",
          actual_arrival=None, delay_days=0,
          linked_mission_id=None, linked_inventory_id="INV-003", linked_asset_id=None,
          container_id="CNT-025"),
    Cargo(id="C-1052", cargo_code="C-1052",
          description="Field Hypothermia Emergency Treatment Units",
          category="Medicine", origin="AIIMS New Delhi",
          destination="STA-01", current_location="Goa Airbase",
          transport_mode="Air", weight=32.0, quantity=4,
          priority="Critical", status="Packed",
          planned_departure="2026-09-14", planned_arrival="2026-09-17",
          actual_arrival=None, delay_days=0,
          linked_mission_id=None, linked_inventory_id="INV-004", linked_asset_id=None,
          container_id="CNT-026"),
    Cargo(id="C-1053", cargo_code="C-1053",
          description="Solar PV Inverter Spares & Cable Arrays",
          category="Equipment", origin="BHEL Hyderabad",
          destination="STA-02", current_location="Maitri Staging Bay",
          transport_mode="Land", weight=68.0, quantity=2,
          priority="Normal", status="At Station",
          planned_departure="2026-09-01", planned_arrival="2026-09-08",
          actual_arrival="2026-09-08", delay_days=0,
          linked_mission_id=None, linked_inventory_id=None, linked_asset_id=None,
          container_id="CNT-027"),
    Cargo(id="C-1054", cargo_code="C-1054",
          description="Sub-zero Synthetic Engine Lubricant (Arctic Spec)",
          category="Fuel", origin="IOCL Haldia",
          destination="STA-03", current_location="STA-01 Transit Staging",
          transport_mode="Land", weight=240.0, quantity=10,
          priority="Normal", status="In Transit",
          planned_departure="2026-09-12", planned_arrival="2026-09-15",
          actual_arrival=None, delay_days=0,
          linked_mission_id="M-045", linked_inventory_id="INV-012", linked_asset_id="A-V06",
          container_id="CNT-028"),
    Cargo(id="C-1055", cargo_code="C-1055",
          description="Emergency High-Calorie Rations Pack (Reserve)",
          category="Food", origin="DFRL Mysore",
          destination="STA-03", current_location="Goa Transit Warehouse",
          transport_mode="Air", weight=110.0, quantity=5,
          priority="High", status="Packed",
          planned_departure="2026-09-15", planned_arrival="2026-09-19",
          actual_arrival=None, delay_days=0,
          linked_mission_id="M-045", linked_inventory_id="INV-013", linked_asset_id=None,
          container_id="CNT-029"),
]

# ─── Missions ────────────────────────────────────────────────────────────────
MISSIONS = [
    Mission(id="M-021", mission_code="M-021",
            mission_name="Geological Survey — Prydz Bay Ice Shelf",
            station_id="STA-03", priority="High", status="Active",
            start_date="2026-09-10", end_date="2026-09-25",
            team="Gamma", required_personnel=4,
            description="Ice core sampling and geological survey of Prydz Bay Ice Shelf Sector B12.",
            objective="Collect ice core samples at depths 50m, 100m, 150m for paleoclimate analysis."),
    Mission(id="M-027", mission_code="M-027",
            mission_name="Generator G-03 Scheduled Maintenance (Task M-14)",
            station_id="STA-01", priority="Critical", status="At Risk",
            start_date="2026-09-18", end_date="2026-09-20",
            team="Alpha", required_personnel=2,
            description="Task M-14: Scheduled overhaul and exciter module replacement for primary generator G-03.",
            objective="Replace exciter module under Task M-14 to maintain 100% power reliability at Bharati Station."),
    Mission(id="M-031", mission_code="M-031",
            mission_name="Meteorological Data Collection",
            station_id="STA-02", priority="Normal", status="Active",
            start_date="2026-09-08", end_date="2026-09-30",
            team="Beta", required_personnel=3,
            description="Continuous atmospheric data collection for NCPOR weather modeling.",
            objective="Deploy and monitor 12 weather stations across the Schirmacher Oasis region."),
    Mission(id="M-038", mission_code="M-038",
            mission_name="Personnel Transfer — Bharati to Field Camp",
            station_id="STA-01", priority="Normal", status="Active",
            start_date="2026-09-13", end_date="2026-09-13",
            team="Alpha", required_personnel=1,
            description="Routine personnel transfer mission using V-02.",
            objective="Transport Tech. Arjun Sharma to Field Camp Alpha for instrument calibration."),
    Mission(id="M-041", mission_code="M-041",
            mission_name="Communication Equipment Inspection",
            station_id="STA-01", priority="Normal", status="Planned",
            start_date="2026-09-16", end_date="2026-09-17",
            team="Alpha", required_personnel=2,
            description="Inspection and calibration of newly arrived satellite relay module.",
            objective="Integrate new satellite relay into primary communication array."),
    Mission(id="M-045", mission_code="M-045",
            mission_name="Emergency Resupply — Field Camp Alpha",
            station_id="STA-01", priority="High", status="Planned",
            start_date="2026-09-19", end_date="2026-09-19",
            team="Command", required_personnel=2,
            description="Emergency fuel and supply resupply to Field Camp Alpha.",
            objective="Restore fuel reserves at Field Camp to safe operational levels."),
]

# ─── Dependencies ────────────────────────────────────────────────────────────
DEPENDENCIES = [
    # C-1042 → INV-017 (cargo delivers inventory)
    Dependency(id="DEP-001", source_type="cargo", source_id="C-1042",
               target_type="inventory", target_id="INV-017",
               relationship_type="delivers", criticality="Critical"),
    # INV-017 → A-G03 (inventory required_for asset maintenance)
    Dependency(id="DEP-002", source_type="inventory", source_id="INV-017",
               target_type="asset", target_id="A-G03",
               relationship_type="required_for", criticality="Critical"),
    # A-G03 → M-027 (asset supports mission)
    Dependency(id="DEP-003", source_type="asset", source_id="A-G03",
               target_type="mission", target_id="M-027",
               relationship_type="supports", criticality="Critical"),
    # M-027 → Team Alpha personnel
    Dependency(id="DEP-004", source_type="mission", source_id="M-027",
               target_type="personnel", target_id="P-004",
               relationship_type="assigned_to", criticality="High"),
    Dependency(id="DEP-005", source_type="mission", source_id="M-027",
               target_type="personnel", target_id="P-005",
               relationship_type="assigned_to", criticality="High"),
    # M-021 dependencies
    Dependency(id="DEP-006", source_type="cargo", source_id="C-1038",
               target_type="mission", target_id="M-021",
               relationship_type="required_by", criticality="High"),
    Dependency(id="DEP-007", source_type="asset", source_id="A-V06",
               target_type="mission", target_id="M-021",
               relationship_type="supports", criticality="High"),
    Dependency(id="DEP-008", source_type="mission", source_id="M-021",
               target_type="personnel", target_id="P-014",
               relationship_type="assigned_to", criticality="High"),
    Dependency(id="DEP-009", source_type="mission", source_id="M-021",
               target_type="personnel", target_id="P-015",
               relationship_type="assigned_to", criticality="High"),
    Dependency(id="DEP-010", source_type="mission", source_id="M-021",
               target_type="personnel", target_id="P-016",
               relationship_type="assigned_to", criticality="High"),
    Dependency(id="DEP-011", source_type="mission", source_id="M-021",
               target_type="personnel", target_id="P-023",
               relationship_type="assigned_to", criticality="Medium"),
    # M-031 dependencies
    Dependency(id="DEP-012", source_type="asset", source_id="A-V05",
               target_type="mission", target_id="M-031",
               relationship_type="supports", criticality="High"),
    Dependency(id="DEP-013", source_type="mission", source_id="M-031",
               target_type="personnel", target_id="P-011",
               relationship_type="assigned_to", criticality="High"),
    Dependency(id="DEP-014", source_type="mission", source_id="M-031",
               target_type="personnel", target_id="P-013",
               relationship_type="assigned_to", criticality="High"),
    # M-038 dependencies
    Dependency(id="DEP-015", source_type="asset", source_id="A-V02",
               target_type="mission", target_id="M-038",
               relationship_type="supports", criticality="High"),
    Dependency(id="DEP-016", source_type="mission", source_id="M-038",
               target_type="personnel", target_id="P-007",
               relationship_type="assigned_to", criticality="High"),
    # M-041 dependencies
    Dependency(id="DEP-017", source_type="asset", source_id="A-C01",
               target_type="mission", target_id="M-041",
               relationship_type="supports", criticality="High"),
    Dependency(id="DEP-018", source_type="mission", source_id="M-041",
               target_type="personnel", target_id="P-008",
               relationship_type="assigned_to", criticality="High"),
    # G-01 supports Bharati operations
    Dependency(id="DEP-019", source_type="asset", source_id="A-G01",
               target_type="mission", target_id="M-041",
               relationship_type="supports", criticality="Medium"),
    # C-1039 → INV-004
    Dependency(id="DEP-020", source_type="cargo", source_id="C-1039",
               target_type="inventory", target_id="INV-004",
               relationship_type="delivers", criticality="High"),
]

# ─── Initial Alerts ──────────────────────────────────────────────────────────
ALERTS = [
    Alert(id="ALT-001", type="cargo_delay", severity="Critical",
          title="Cargo C-1042 Critically Delayed",
          message="Generator Exciter Module (C-1042) delayed by 5 days at Colombo Transit Port. Mission M-027 at risk.",
          entity_type="cargo", entity_id="C-1042",
          created_at=datetime(2026, 9, 13, 7, 12, 0), acknowledged=False),
    Alert(id="ALT-002", type="inventory_critical", severity="Critical",
          title="Generator Exciter Module — Out of Stock",
          message="INV-017 (Generator Exciter Module) at zero units at Bharati. Required for M-027 maintenance.",
          entity_type="inventory", entity_id="INV-017",
          created_at=datetime(2026, 9, 13, 7, 15, 0), acknowledged=False),
    Alert(id="ALT-003", type="mission_risk", severity="High",
          title="Mission M-027 At Risk",
          message="Generator G-03 maintenance mission (M-027) at risk due to cargo C-1042 delay.",
          entity_type="mission", entity_id="M-027",
          created_at=datetime(2026, 9, 13, 7, 16, 0), acknowledged=False),
    Alert(id="ALT-004", type="inventory_critical", severity="High",
          title="Medical Kits Below Minimum — Bharati",
          message="Medical Kit inventory (INV-004) at Bharati is 5 units, below minimum of 10. Resupply in transit.",
          entity_type="inventory", entity_id="INV-004",
          created_at=datetime(2026, 9, 13, 8, 0, 0), acknowledged=False),
    Alert(id="ALT-005", type="asset_failure", severity="Medium",
          title="Vehicle V-03 In Maintenance",
          message="Snow Vehicle V-03 is in scheduled maintenance at Maitri. Available personnel transport capacity reduced.",
          entity_type="asset", entity_id="A-V03",
          created_at=datetime(2026, 9, 13, 9, 0, 0), acknowledged=True),
    Alert(id="ALT-006", type="inventory_critical", severity="Medium",
          title="Field Camp Alpha — Low Fuel Alert",
          message="Diesel fuel at Field Camp Alpha (1,800L) approaching minimum. Next resupply in 5 days.",
          entity_type="inventory", entity_id="INV-012",
          created_at=datetime(2026, 9, 13, 10, 30, 0), acknowledged=False),
    Alert(id="ALT-007", type="mission_risk", severity="Low",
          title="G-03 Maintenance Window Closing",
          message="Generator G-03 maintenance due by 2026-09-18. Parts delay may cause overdue operation.",
          entity_type="asset", entity_id="A-G03",
          created_at=datetime(2026, 9, 13, 11, 0, 0), acknowledged=False),
]

# ─── Initial Active Disruptions ──────────────────────────────────────────────
DISRUPTIONS = [
    Disruption(
        id="DIS-001",
        disruption_code="DIS-20260913-001",
        type="cargo_delay",
        entity_type="cargo",
        entity_id="C-1042",
        severity="Critical",
        description="5-day shipping delay on Cargo C-1042 (Exciter Module for G-03 Generator).",
        parameters='{"delay_days": 5}',
        status="Active",
        is_simulation=False,
        created_at=datetime(2026, 9, 13, 7, 10, 0)
    )
]

# ─── Audit Logs ──────────────────────────────────────────────────────────────
AUDIT_LOGS = [
    AuditLog(id=str(uuid.uuid4()),
             timestamp=datetime(2026, 9, 13, 7, 10, 0),
             action="cargo_delay_detected",
             entity_type="cargo", entity_id="C-1042",
             description="Cargo C-1042 delay of 5 days detected. New ETA: 2026-09-20.",
             user_role="System"),
    AuditLog(id=str(uuid.uuid4()),
             timestamp=datetime(2026, 9, 13, 7, 12, 0),
             action="alert_created",
             entity_type="cargo", entity_id="C-1042",
             description="Critical alert created for cargo C-1042 delay.",
             user_role="System"),
    AuditLog(id=str(uuid.uuid4()),
             timestamp=datetime(2026, 9, 13, 7, 15, 0),
             action="alert_created",
             entity_type="inventory", entity_id="INV-017",
             description="Critical inventory alert: Generator Exciter Module out of stock.",
             user_role="System"),
    AuditLog(id=str(uuid.uuid4()),
             timestamp=datetime(2026, 9, 13, 8, 0, 0),
             action="system_startup",
             entity_type="system", entity_id="POLAROPS",
             description="POLAROPS system initialized. Synthetic demonstration data loaded.",
             user_role="System"),
]


async def seed():
    from models import models  # register models
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

    async with AsyncSessionLocal() as session:
        # Insert in dependency order
        for s in STATIONS:
            session.add(s)
        await session.flush()

        for p in PERSONNEL:
            session.add(p)
        for a in ASSETS:
            session.add(a)
        for inv in INVENTORY:
            session.add(inv)
        await session.flush()

        for c in CARGO:
            session.add(c)
        for m in MISSIONS:
            session.add(m)
        await session.flush()

        for d in DEPENDENCIES:
            session.add(d)
        for dis in DISRUPTIONS:
            session.add(dis)
        for al in ALERTS:
            session.add(al)
        for log in AUDIT_LOGS:
            session.add(log)

        await session.commit()
        print("[OK] POLAROPS seed data loaded successfully.")
        print(f"   Stations: {len(STATIONS)} | Personnel: {len(PERSONNEL)} | Assets: {len(ASSETS)}")
        print(f"   Inventory: {len(INVENTORY)} items | Cargo: {len(CARGO)} consignments | Missions: {len(MISSIONS)}")
        print(f"   Dependencies: {len(DEPENDENCIES)} | Alerts: {len(ALERTS)}")
        print("")
        print("[NOTE] SYNTHETIC / SIMULATED PROTOTYPE DATA")
        print("   Not actual NCPOR operational data.")


if __name__ == "__main__":
    asyncio.run(seed())
